import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import dayjs from "dayjs";

import { data } from "../data/data";

export default function Home({ data }) {
  console.log(`data: `, data);

  let tmpData = data;

  let m = tmpData.filter((i) => i.zimufabu.length === 0);
  let n = tmpData.filter((i) => i.zimufabu.length !== 0);

  n = n.sort((a, b) =>
    new Date(formatDate(a.zimufabu)) < new Date(formatDate(b.zimufabu)) ? 1 : -1
  );
  let ordered = m.concat(n);

  const hashCode = (s) =>
    s.split("").reduce((a, b) => ((a << 5) - a + b.charCodeAt(0)) | 0, 0);

  function getChannel(url) {
    let str = ``;

    if (url.match(/acfun/g)) {
      str = `AcFun`;
    } else if (url.match(/bili/g)) {
      str = `Bilibili`;
    } else {
      str = `Weibo`;
    }

    return str;
  }
  function getLink(i) {
    return i.shipin.map((j) => (
      <li className={getChannel(j).toLowerCase()} key={j}>
        <Link href={j}>{getChannel(j)}</Link>
      </li>
    ));
  }
  function formatDate(Date) {
    let tmp = `20` + Date.replace(/\/|\//g, "-");
    return dayjs(tmp).format("MMM DD, YYYY");
  }

  return (
    <Layout>
      <Head>
        <title>水山汉化纪录片字幕目录</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <header className="flex flex-col items-center justify-center space-x-2">
          <h1>水山汉化纪录片字幕目录</h1>
          <span>（共 {data.length} 部）</span>
        </header>

        <dl className="social-link">
          <dt>微博 :</dt>
          <dd>
            <a href="https://www.weibo.com/u/5872636712">@水山水山水山</a>
          </dd>
          <dt>微博话题 :</dt>
          <dd>
            <a href="https://s.weibo.com/weibo?q=%23%E6%B0%B4%E5%B1%B1%E6%B1%89%E5%8C%96%23">
              #水山汉化#
            </a>
          </dd>
          <dt>A站UP主 :</dt>
          <dd>
            <a href="https://www.acfun.cn/u/7309595.aspx">水山水山水山</a>
          </dd>
          <dt>B站UP主 :</dt>
          <dd>
            <a href="https://space.bilibili.com/16152305/video">altabili</a>
          </dd>
        </dl>
        <div className="table-container">
          <table className="w-full">
            <thead>
              <tr className="flex w-full items-center space-x-5 bg-blue-900 p-2 text-left text-xs">
                <th className="w-20">片厂</th>
                <th className="grow">片名</th>
                <th className="w-12">年份</th>
                <th className="w-24">字幕发布</th>
                <th className="w-20">微博</th>
                <th className="w-48">视频</th>
                <th className="w-20">ED2K</th>
              </tr>
            </thead>
            <tbody className="w-full divide-y divide-blue-700">
              {ordered
                .sort((a, b) =>
                  new Date(formatDate(a.zimufabu)) <
                  new Date(formatDate(b.zimufabu))
                    ? 1
                    : -1
                )
                .map((i, index) => (
                  <tr
                    className="flex w-full items-center space-x-5 p-2 hover:bg-blue-700"
                    key={hashCode(i.eng + index)}
                  >
                    <td className="w-20">{i.pianchang}</td>
                    <td className="title">
                      <h3 className="chinese">{i.all}</h3>
                      <h3 className="english">{i.eng}</h3>
                    </td>
                    <td className="year w-12">{i.nianfen ?? `-`}</td>
                    <td className="date">
                      {i.zimufabu ? formatDate(i.zimufabu) : `-`}
                    </td>
                    <td className="weibo-link">
                      {i.weibo ? (
                        <Link href={i.weibo}>
                          <span className="sr-only">Weibo</span>
                        </Link>
                      ) : (
                        `-`
                      )}
                    </td>
                    <td className="w-48">
                      {i.shipin.length !== 0 ? (
                        <ul className="video-link">{getLink(i)}</ul>
                      ) : (
                        `-`
                      )}
                    </td>
                    <td className="w-20">
                      {i.ed2k !== null ? (
                        <a className="download" href={i.ed2k}>
                          ED2K
                        </a>
                      ) : (
                        `-`
                      )}
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </div>
    </Layout>
  );
}

export const getStaticProps = async (ctx) => {
  return {
    props: {
      data: data,
    },
  };
};
